### ISSUE TITLE
Issue with images that have max-width: 100%

### ISSUE THREAD

**Issue by FernE97** [tsvensen/equalize.js#10]
When there is an image with `max-width: 100%; height: auto;` for responsiveness, the height of the columns don't always get calculated correctly. Sometimes it loads correctly and the height of the columns are fine, and other times the content overflows the container since the height is too little. I also notice when I refresh the page, the majority of the time, the boxes don't get calculated correctly. I could be setting it up wrong, but I can't figure out how to get it to always display properly. Thanks

I setup an example on codepen.

code: http://codepen.io/FernE97/pen/dquwy

full: http://codepen.io/FernE97/full/dquwy

**Comment by sveetch** [comment]
Hi,

I've tested http://s.codepen.io/FernE97/fullpage/dquwy on Firefox 19 Linux, Chromium 25 Linux, Internet Explorer 9, Safari 5.1.7 Windows, Firefox 16 Windows, Chrome Android and the height is always right (content correctly fit in their container that have all the same height).

But when i test directly http://codepen.io/FernE97/pen/dquwy which use an iframe, effectively the containers have not the same height and some content are over their container.

If i test http://codepen.io/FernE97/pen/dquwy, it only fails on IE 9.

Which browsers are giving you the bad behavior ?

**Comment by tsvensen** [comment]
One option is to call equalize after the images have finished loading, that might solve the issue.

https://github.com/desandro/imagesloaded

**Comment by Fatbat** [comment]
I'll certainly look at the imagesloaded script, but are there any other solutions you can think of? This is a problem with any image where their height isn't defined or is set to auto. It occurs in all the latest versions of every major browser. sveetch's first examples above do the same thing. It's obviously affected by things like page size and internet speeds so not every person is going to experience the same thing every time. Thanks.

**Comment by Fatbat** [comment]
Is this not functionality that should be included in this script? I have many instances where I want to equalize columns that only contain images. To me it makes sense that equalize.js should work with any content in the columns without the need of another 3rd party script. I'd love to hear your opinion @tsvensen
