### ISSUE TITLE
Include margin from children elements in height

### ISSUE THREAD

**Issue by KZeni** [tsvensen/equalize.js#15]
I have a container with a set of paragraphs being equalized. Problem is that the paragraphs have margin on them, and that isn't being included in the height when equalized. I'm using the outerHeight option, but that still doesn't include the margin.

outerHeight actually has a boolean option for determining whether or not to include the margin & it isn't included by default. I'm wondering if there could be an option added to this allowing people to include the margin if needed.

**Comment by KZeni** [comment]
Ah, I see that outerHeight doesn't capture the margin on children elements even with this option enabled. I'll opt instead to simply add that margin to the container as well so it doesn't jump after getting the margin of the child element cut off by the forced height.

Maybe there is a way to get jQuery to include the margin of children in the calculated height... I suppose I'll leave it as a feature request.

**Comment by KZeni** [comment]
So... I actually found a way to add this functionality into this plugin as a option in 244 bytes or so. You can see my proposed addition here: https://github.com/tsvensen/equalize.js/pull/16

**Comment by johnw86** [comment]
Thanks for this just solved my issue.
