### ISSUE TITLE
Does not work with responsive/undefined dimension images

### ISSUE THREAD

**Issue by Fatbat** [tsvensen/equalize.js#18]
Since my questions/comments in the closed thread have gone unanswered I guess I need to start a new one. equalize.js does not work with images that do not have height defined, as is the case with responsive images that have max-width: 100%; and height: auto; set. If the images aren't loaded before equalize.js fires, it equalizes the columns without taking the image into consideration. The behavior is the same in all the latest browsers. The script sometimes works and sometimes does not, depending on connection speeds, number of images on the page, etc. You can hit reload over and over sometimes getting the desired result and sometimes a broken page.

I would argue that this script should work regardless of the type of content in the equalized container. I tried the https://github.com/desandro/imagesloaded script, following the instructions for the jQuery implementation, but it doesn't seem to work.

I also tried adding a window load function to fire equalize or smartresize, but that didn't work.

If you've got any suggestions, perhaps an example bit of code that does work, it would be greatly appreciated.

@tsvensen please help!

**Comment by Fatbat** [comment]
I actually got this working with window load, but now there's a definite jump, fouc or whatever, once the page loads and the columns equalize.

**Comment by Fatbat** [comment]
No advice or comments? I could really use some help. I just can't figure out how to get this script working with responsive images and not have a nasty jump when everything equalizes.

**Comment by Fatbat** [comment]
Anyone at all?

**Comment by britzke** [comment]
It seem that there is no one there. Last commit one year ago. Two pull requests left open for 7 month... This may be a candidate for a fork.

**Comment by tsvensen** [comment]
@Fatbat, I think you were going down the right path with imagesLoaded.

```
var $container = $('#container');
imagesLoaded( $container[0], function( instance ) {
  // All images loaded
  $container.equalize();
});
```

For an example of using equalize responsively checkout [ESRG](http://dfcb.github.io/extra-strength-responsive-grids/):
- https://github.com/dfcb/extra-strength-responsive-grids/blob/master/index.html#L461-L468

**Comment by Fatbat** [comment]
@tsvensen I'm just not getting this. I've tried the Images Loaded script, but it just doesn't do anything. This is the configuration I have for my equalize.js. I'm using Bootstrap, so am putting the .equal class on the rows in which I want columns to be equal (or wells). It works great, except for columns with images in them that don't have a defined height. Clearly I'm not understanding how to implement the code above properly. Any help would be greatly appreciated.

I had a look at the ESRG thing, I think you might have mentioned it before in a previous issue when you guys pointed out the smartresize thing. I've got equalize working responsively, it's just the images that are causing me grief.

```
    // equal height divs in a row
    $.fn.equalize = function(options) {
        var $containers = this,
            // this is the jQuery object
            children = false,
            reset = false,
            equalize, type;

        // when options are an object
        if ($.isPlainObject(options)) {
            equalize = options.equalize || 'height';
            children = options.children || false;
            reset = options.reset || false;
        } else { // otherwise, a string was passed in or default to height
            equalize = options || 'height';
        }

        if (!$.isFunction($.fn[equalize])) {
            return false;
        }

        // determine if the height or width is being equalized
        type = (equalize.indexOf('eight') > 0) ? 'height' : 'width';

        return $containers.each(function() {
            // when children exist, equalize the passed in child elements, otherwise equalize the children
            var $children = (children) ? $(this).find(children) : $(this).children(),
                max = 0; // reset for each container

            $children.each(function() {
                var $element = $(this),
                    value;
                if (reset) {
                    $element.css(type, '');
                } // remove existing height/width dimension
                value = $element[equalize](); // call height(), outerHeight(), etc.
                if (value > max) {
                    max = value;
                } // update max
            });

            if ($(window).width() > 768) $children.css(type, max + 'px'); // add CSS to children
            else $children.css(type, '');

        });
    };

    // smart resize - http://paulirish.com/2009/throttled-smartresize-jquery-event-handler/
    (function($, sr) {

        // debouncing function from John Hann
        // http://unscriptable.com/index.php/2009/03/20/debouncing-javascript-methods/
        var debounce = function(func, threshold, execAsap) {
            var timeout;

            return function debounced() {
                var obj = this,
                    args = arguments;

                function delayed() {
                    if (!execAsap) func.apply(obj, args);
                    timeout = null;
                };

                if (timeout) clearTimeout(timeout);
                else if (execAsap) func.apply(obj, args);

                timeout = setTimeout(delayed, threshold || 100);
            };
        }
        // smartresize
        jQuery.fn[sr] = function(fn) {
            return fn ? this.bind('resize', debounce(fn)) : this.trigger(sr);
        };

    })(jQuery, 'smartresize');

    $(function() {
        // use equalize to equalize the heights of content elements
        $('.equal').equalize({
            children: '[class*="col-"], .well',
            equalize: 'outerHeight'
        });

        // re-equalize on resize
        $(window).smartresize(function() {
            console.log('smartresize');
            $('.equal').equalize({
                reset: true,
                children: '[class*="col-"], .well'
            });
        });
    });
```
