### ISSUE TITLE
Add option to "unequalize"

### ISSUE THREAD

**Issue by g-liu** [tsvensen/equalize.js#20]
Equalize is great, but what if the user resizes their browser window and we want to "unequalize" the heights? For this, there should be an `unequalize()` function.

**Comment by SahilMepani** [comment]
Yes, this has been a problem. Is there a way we could equalize when the window resizes.

**Comment by tsvensen** [comment]
You can run equalize on resize. I recommend using a debounced/throttled solution from [Ben Alman](http://benalman.com/projects/jquery-throttle-debounce-plugin/) or [Lodash](http://lodash.com/docs#throttle)/[Underscore](http://underscorejs.org/#throttle).  So equalize would run within the throttled function.

**Comment by beyond-definition** [comment]
use enquire.js and  remove the height 
   unmatch : function() {
 $('div').height('');

 }

**Comment by beyond-definition** [comment]
I think it really needs destroy function.

**Comment by RienMoeyaert** [comment]
Something like `$(".target").equalize("destroy");` would be great indeed
