### ISSUE TITLE
Equalize on page resize part 2

### ISSUE THREAD

**Issue by Fatbat** [tsvensen/equalize.js#7]
Forgive me, I'm a jQuery noob. I am initializing the script with:

```
$('.row').equalize({children: '.equal'});
```

Which works great for the initial equalization. However, this doesn't do anything when resizing the window:

```
$(window).resize(function() { $('.row').equalize({children: '.equal'}); });
```

What am I doing wrong?

**Comment by tsvensen** [comment]
Everything looks good to me, especially if it's working on the initial page load. Your resize function looks correct. I really can't help beyond that as does not appear to be an issue with equalize.

Take a look at Extra Strength Responsive Grids for an example of equalize working on resize.  It's near the bottom of the page: http://dfcb.github.com/extra-strength-responsive-grids/

**Comment by johnpolacek** [comment]
Yeah, definitely use the smartresize function for debouncing. 
http://paulirish.com/2009/throttled-smartresize-jquery-event-handler/

**Comment by Fatbat** [comment]
OK, added the smartresize (thank you very much!) and the initializing method used on the Extra Strength Grids and it seems to be working good. I have one other issue now though and that is a media query breakpoint at <768 where elements stack. I'd like previously side by side equalized elements to forget that they are equalized below this point now that they are stacked. Any ideas?

Thanks for your help, it's greatly appreciated.
